---
title: "Week 4"
subtitle: "Data wrangling & tidying"
author: "Dani Cosme"
output:
  xaringan::moon_reader:
    css: ["default", "css/dcos.css", "css/dcos-fonts.css"]
    lib_dir: libs
    nature:
      highlightStyle: atelier-lakeside-light
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, 
  comment = NA, dpi = 300,
  fig.align = "center", out.width = "80%", cache = FALSE)

if(!require('tidyverse')) {
	install.packages('tidyverse')
}
if(!require('devtools')) {
	install.packages('devtools') 
}
if(!require('emo')) {
	devtools::install_github("hadley/emo")
}
if(!require('xaringanExtra')) {
	devtools::install_github("gadenbuie/xaringanExtra")
}
if(!require('countdown')) {
	devtools::install_github("gadenbuie/countdown")
}
```

## Check-in

--

### Email feedback

* If you haven't yet given feedback, please do

--

* Let's incorporate the feedback and finalize the emails by **Wednesday, March 31**

---

## Check-in
### Survey drafting

Brainstorm and current plan is [here](https://docs.google.com/document/d/1_JyRfddJ4pByrOG-eOQQkfz7deR59yTjjS3O8Y-39l8/edit?usp=sharing)

--

Next steps:

* Tasks to complete by **Wednesday, March 31**

--
  
  * Draft messages (5 per condition)
  
--
  
  * Draft open-ended questions & decide which ones to include
  
--
  
  * Update the Qualtrics survey
  
--
  
* Tasks to complete by **Friday, April 2**

--
  
  * Take the survey
  
--

  * Give feedback using [this doc](https://docs.google.com/document/d/1H1_B-Mrr-GyrhbHOlvRScAX0RNsa0T_9eG7xxSwVYug/edit?usp=sharing)

---
class: center, middle

## Goal for this week

Get our feet wet with data wrangling and tidying in R<br><br>

---
## Background

Dataset

* Study about civic engagement, motivation, and voting behavior

--

* Collected after the election via the Psychology Human Subject Pool

--

* Used both survey measures and open-ended questions

---
class: center, middle

## Let's walk through the [week4.Rmd](../labs/week4.html) code together

---
## Assignment

--

1. Run through the code we walked through together on your own in the `week4.Rmd`

--

2. Apply what you've learned in the assignment section of the `week4.Rmd`

--

3. Post to Slack for collective troubleshooting

--

4. Use the `week4_key.Rmd` to check your solutions

